@startuml
scale 0.8

hide empty description

CREATE:
state READY_TO_PRINT {

    state printGuard <<inputPin>>
}

state READY_TO_SIGN {
    state signGuard <<inputPin>>
}
state SIGN_CHECK <<choice>>
SIGNED:bla-bla-bla

state ECM_FOLDER {
    state ecmFolderGuard <<inputPin>>
}


SLA_ERROR:

[*] -[dashed]-> CREATE : init

CREATE -[bold]-> printGuard : check_ready_to_print
READY_TO_PRINT -[bold]-> signGuard : check_ready_to_sign
READY_TO_SIGN -[bold]-> SIGN_CHECK : sign
SIGN_CHECK -[dashed]-> ERROR : checkSign=False
SIGN_CHECK -[dashed]-> SIGNED : checkSign=True
SIGNED -[dashed]-> ecmFolderGuard : on_time_event



SIGNED -[dashed]-> SLA_ERROR : sla_error
ECM_FOLDER -[dashed]-> SLA_ERROR : sla_error


CREATE -[dotted]-> [*] : exit_event
READY_TO_PRINT -[dotted]-> [*] : exit_event
READY_TO_SIGN -[dotted]-> [*] : exit_event
ERROR -[dashed]-> [*] : on_time_event
SLA_ERROR --> [*] : on_time_event
@enduml