@startuml
scale 0.9

hide empty description

SIGNED:CHOICE
SLA_ERROR:

[*] --> CREATE : init

CREATE --> READY_TO_PRINT : try_print
READY_TO_PRINT --> READY_TO_SIGN : try_sign
READY_TO_SIGN --> SIGNED : sign_event
SIGNED --> ECM_FOLDER_CREATE : ecm_callback
SIGNED --> ERROR :error_event
SIGNED -[dotted]-> SLA_ERROR : sla_error


CREATE -[dotted]-> [*] : exit_event
READY_TO_PRINT -[dotted]-> [*] : exit_event
READY_TO_SIGN -[dotted]-> [*] : exit_event
ERROR --> [*] : on_time_event
SLA_ERROR --> [*] : on_time_event
@enduml